### ISSUE TITLE
Include: directive ignored when using plugin.

### ISSUE THREAD

**Issue by rjoycegehtsoft** [fralau/mkdocs-macros-plugin#178]
I am using this plugin to get variable usage.
Eg, if I am viewing page /documents/test.html which contains a link to another page, /examples/example1.html
without this plugin, it will render the link as http://127.0.0.1:8000/documents/examples/example1.html
so to solve this, I have a variable in the extra section: basde_url: http://127.0.0.1:8000/
then I create the link using` [go to example 1]({{base_url}}/examples/example1.md) `
and this works. and **thank you** for that.
My problem is that I have hundreds of pages that I do not want as part of the nav tree.
for example if I have a page that contains a list of methods in a class, the link to the class page IS in the nav tree, but I don't want the methods to be in the nav tree as it will get too cluttered, so, I create a file in the folder where that classes md file is named classname.methodname.md
These hundreds of files with this format, I do not want in the nav tree so I use the include: directive in my mkdocs.yml file so that mkdocs will convert them to html
when not using the mactos plugin, the includes directive works and the files are converted to html, however when it is used, the include directive is ignored and the files are not created.

**Comment by rjoycegehtsoft** [comment]
Thanks. I'm happy to make a small donation if need be to help get ths resolved as this is the last item in my project to be resolved.

**Comment by fralau** [comment]
To better understand the problem, I need more information on the context. What is the goal and function of the module that you wrote? 

I am asking, because you mentioned you have hundred of files in your nav tree. There is a problem right there: in MkDocs, the nav tree is for files that will go into the website. 

Is your program is scanning through the directory tree of a software project, or something similar? If that is the case, that directory tree should _not_ be in the docs dir; you should move it in a parallel directory (still under your `mkdocs.yaml`). 

For the question: "when not using the macros plugin, the includes directive works and the files are converted to html, however when it is used, the include directive is ignored and the files are not create", to which include directive are you referring to?

**Comment by fralau** [comment]
@rjoycegehtsoft  Is this issue still open? Did you find another solution?
