### ISSUE TITLE
Plugin incorrectly demands existence of `define_env()` in module

### ISSUE THREAD

**Issue by fralau** [fralau/mkdocs-macros-plugin#191]
There is a requirement in the [plugin.py file](https://github.com/fralau/mkdocs_macros_plugin/blob/7b71e2566f391af03f8ba9965645d701b0d37770/mkdocs_macros/plugin.py#L408) that the `define_env()` function should be present in the module file (`main.py`).

This was correct in the past, but nowadays it could also be `on _pre_page_macros` and others.

### Workaround
Just add this function to the module file:

```python
def define_env(env):
   pass
```

**Comment by fralau** [comment]
Any standard function is now accepted and the error is now explicit in case none is found:

```
NameError: None of the standard functions was found in module 'main':
['define_env', 'on_pre_page_macros', 'on_post_page_macros', 'on_post_build']
```

For good measure, module also traces now when no module is found (it's not an error, just in case someone gave a wrong name to the module, or put it in the wrong place).

**Comment by fralau** [comment]
@Andre601 Could you please check that it works for you now?

**Comment by Andre601** [comment]
Tho, I have to add that in my case, the `on_pre_page_macros` call doesn't work right? Or at least not how I want it to?

I want it to add `{% import 'game.md' as game %}` to the markdown itself, so that I can them use macros without having to import them first, but either the markdown isn't modified, or the import statement isn't seen as such...

The full code I use, which is basically a copy of the docs:
```py
def on_pre_page_macros(env):
    footer = "{% import 'game.md' as game %}"
    env.markdown += footer
```
I also tried putting it in front of the env.markdown (At the top) in hopes that it may be an issue with order, but no luck there.

It simply gives a "game is undefined" error...

**Comment by fralau** [comment]
It depends on what your expectancy is of "to work".

It is a legitimate statement, which will be executed immediately after. Indeed, it is executed (at least your error seems to be a jinja2 error). Your import statement seems incorrected formulated ([see examples](https://ttl255.com/jinja2-tutorial-part-6-include-and-import/#import-statement)):

Shouldn't it be something like the following?

```jinja2
{% from 'game.md' import game %}
```

**Comment by Andre601** [comment]
I've used jinja2 more than enough to know that `{% import ... as ... %}` works here.

Also, my fault for not mentioning that it does work, but I had to add it at the top of the page due to how jinja2 parses things.
